name: Test-Run Do Not Submit Action
on:
  pull_request:
    branches:
      - main
      - ci/test # i messed something up and ci/test is the base branch oops...
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0 # Check out current PR to get changes compared to main branch
        - name: Run do-not-submit action
          uses: infocus7/do-not-submit-action@fbd272ebe5cb5ff201f4c1199248cbd68e558114
