name: Test-Run Do Not Submit Action
on:
  pull_request:
    branches:
      - main
      - ci/test # i messed something up and ci/test is the base branch oops...
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0 # Check out current PR to get changes compared to main branch
        - name: Run do-not-submit action
          uses: infocus7/do-not-submit-action@518c1113aa4afd9121666760e1fe5fe330110d70
          with:
            keyword: 'DO_NOT_SUBMIT'
            check_list: '"test/data/*"' # Wrapped in quotes, so the wildcard is not expanded by the shell.
            ignore_list: '""'
            should_fail: 'true'
            smart_search: 'false'
