name: Test-Run Do Not Submit Action
on:
  pull_request:
    branches:
      - main
      - ci/test # i messed something up and ci/test is the base branch oops...
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
        - name: Checkout do-not-submit repo
          uses: actions/checkout@v3
          with:
            repository: infocus7/do-not-submit-action # checkout action repo to get the `do-not-submit.sh` script
            sparse-checkout: 'do-not-submit.sh' # only checkout the script
            fetch-depth: 0
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0 # Check out current PR to get changes compared to main branch
        - name: Run do-not-submit action
          uses: infocus7/do-not-submit-action@95c109ad94b4eaf00e42f7ef0afdbfda4a32c80c
          with:
            keyword: 'DO_NOT_SUBMIT'
            check_list: 'test/data/*'
