name: Test-Run Do Not Submit Action
on:
  pull_request:
    branches:
      - main
      - ci/test # i messed something up and ci/test is the base branch oops...
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Run do-not-submit action
          uses: infocus7/do-not-submit-action@95c109ad94b4eaf00e42f7ef0afdbfda4a32c80c
          with:
            keyword: 'DO_NOT_SUBMIT'
            check_list: 'test/data/*'
