name: Test-Run Do Not Submit Action
on:
  pull_request:
    branches:
      - main
      - ci/test # i messed something up and ci/test is the base branch oops...
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0 # Check out current PR to get changes compared to main branch
        - name: Run do-not-submit action
          uses: infocus7/do-not-submit-action@da84217b10d0c909cc72fb0c85d397e68d4cfeef
          with:
            keyword: 'DO_NOT_SUBMIT'
            should_fail: 'true'
            smart_search: 'true'
